server:
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol_header: x-forwarded-proto

spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;Mode=Oracle'

  h2:
    console:
      enabled: true

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
          issuer-uri:

graceful:
  shutdown:
    enabled: false

