
DELETE FROM REF_ASS_VERSION where REF_ASS_VERSION_UK = 100;

DELETE FROM REF_SECTION where REF_SECTION_UK = 9000;

DELETE FROM REF_QUESTION where REF_QUESTION_UK = 9000;

DELETE FROM REF_ANSWER where REF_ANSWER_UK = 9000;
